name: Pre Merge Checks

on: [pull_request]

permissions:
  contents: read

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        # Mac OS and Windows are turned off: https://github.com/Citi/gradle-helm-plugin/issues/5
        os: [ ubuntu-latest ]
        jdk: [ 8, 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#using-the-gradle-starter-workflow
      - name: Checkout Repo
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      # https://github.com/marketplace/actions/gradle-wrapper-validation
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # https://github.com/marketplace/actions/gradle-build-action
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          arguments: build --stacktrace --info

  dependency-review:
    needs: gradle
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          fail-on-severity: high
          allow-licenses: MIT
          fail-on-scopes: development, runtime
